repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Use the latest version compatible with your setup
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy . --config-file="pyproject.toml"
        language: system
        pass_filenames: false

