[project]
name = "fpl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "marimo>=0.11.0",
    "orjson>=3.10.15",
    "polars>=1.22.0",
    "requests>=2.32.3",
    "ruff>=0.9.5",
]
